package com.presupuesto.comun.excepcion;

public enum CodigoError {
    RECURSO_NO_ENCONTRADO,
    CONFLICTO,
    REGLA_NEGOCIO_VIOLADA,
    DATOS_INVALIDOS,
    NO_AUTENTICADO,
    ACCESO_DENEGADO,
    EMAIL_YA_REGISTRADO,
    CREDENCIALES_INVALIDAS,
    PRESUPUESTO_YA_EXISTE,
    CUENTA_YA_EXISTE
}
