spring.application.name=backend

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:presupuesto}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:admin}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
